version: '3'

services:
  pg:
    image: postgres:9.5
    environment:
      POSTGRES_DB: "dataservice"
    ports:
        - "5432:5432"
  dataservice:
    build: .
    command: /bin/ash -c "sleep 5; ./bin/run.sh"
    volumes:
      - .:/app
    ports:
      - "1081:80"
    environment:
      - FLASK_CONFIG=development
      - PG_NAME=dataservice
      - PG_HOST=pg
    depends_on:
      - pg
