"""Increase field size for total reads

Revision ID: 025cf1ee0adf
Revises: 7ed804d54566
Create Date: 2021-01-19 10:59:42.280704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025cf1ee0adf'
down_revision = '7ed804d54566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sequencing_experiment', 'total_reads',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sequencing_experiment', 'total_reads',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
