"""
1.24.0 Add request link and instructions for study biobank

Revision ID: 0454317cd224
Revises: c2f77debb22d
Create Date: 2024-06-20 08:23:43.813232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0454317cd224'
down_revision = 'c2f77debb22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column(
        'biobank_request_instructions', sa.Text(), nullable=True))
    op.add_column('study', sa.Column(
        'biobank_request_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'biobank_request_link')
    op.drop_column('study', 'biobank_request_instructions')
    # ### end Alembic commands ###
