"""
Add alias_group table 

Revision ID: 04c620f9f768
Revises: 6c5b80679ee3
Create Date: 2018-04-12 13:00:45.275774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import dataservice

# revision identifiers, used by Alembic.
revision = '04c620f9f768'
down_revision = '6c5b80679ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias_group',
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('kf_id', dataservice.api.common.model.KfId(length=11), nullable=False),
    sa.PrimaryKeyConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('participant', sa.Column('alias_group_id', dataservice.api.common.model.KfId(length=11), nullable=True))
    op.alter_column('participant', 'family_id',
               existing_type=sa.TEXT(),
               type_=dataservice.api.common.model.KfId(length=11),
               existing_nullable=True)
    op.create_foreign_key(None, 'participant', 'alias_group', ['alias_group_id'], ['kf_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.alter_column('participant', 'family_id',
               existing_type=dataservice.api.common.model.KfId(length=11),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('participant', 'alias_group_id')
    op.drop_table('alias_group')
    # ### end Alembic commands ###
