"""empty message

Revision ID: 066e3d042bdc
Revises: 2065a5e939dd
Create Date: 2018-02-20 21:13:16.702736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066e3d042bdc'
down_revision = '2065a5e939dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('investigator_id', sa.String(length=8), nullable=True))
    op.create_foreign_key(None, 'study', 'investigator', ['investigator_id'], ['kf_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'investigator_id')
    # ### end Alembic commands ###
