"""
1.2.0- Add biospecimen_genomic_file association table

Revision ID: 088f00b10226
Revises: ce359a457d3d
Create Date: 2018-07-12 07:41:56.857583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import dataservice
# revision identifiers, used by Alembic.
revision = '088f00b10226'
down_revision = 'ce359a457d3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biospecimen_genomic_file',
                    sa.Column('uuid', postgresql.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(), nullable=True),
                    sa.Column('genomic_file_id', dataservice.api.common.model.KfId(
                        length=11), nullable=False),
                    sa.Column('biospecimen_id', dataservice.api.common.model.KfId(
                        length=11), nullable=False),
                    sa.Column('kf_id', dataservice.api.common.model.KfId(
                        length=11), nullable=False),
                    sa.ForeignKeyConstraint(['biospecimen_id'], [
                                            'biospecimen.kf_id'], ),
                    sa.ForeignKeyConstraint(['genomic_file_id'], [
                                            'genomic_file.kf_id'], ),
                    sa.PrimaryKeyConstraint('kf_id'),
                    sa.UniqueConstraint('genomic_file_id', 'biospecimen_id'),
                    sa.UniqueConstraint('uuid')
                    )
    op.drop_constraint('genomic_file_biospecimen_id_fkey',
                       'genomic_file', type_='foreignkey')
    op.drop_column('genomic_file', 'biospecimen_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_file', sa.Column('biospecimen_id',
                                            sa.VARCHAR(length=11), autoincrement=False, nullable=True))
    op.create_foreign_key('genomic_file_biospecimen_id_fkey',
                          'genomic_file', 'biospecimen', ['biospecimen_id'], ['kf_id'])
    op.drop_table('biospecimen_genomic_file')
    # ### end Alembic commands ###
