"""
Add release_status to study

Revision ID: 0ab7fe177917
Revises: 6bee334483a5
Create Date: 2018-03-29 14:25:15.764886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab7fe177917'
down_revision = '6bee334483a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('release_status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'release_status')
    # ### end Alembic commands ###
