"""Initial migration

Revision ID: 0cc35a21afc2
Revises: 
Create Date: 2018-02-02 12:51:49.699860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc35a21afc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('demographic',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('race', sa.Text(), nullable=True),
    sa.Column('ethnicity', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('participant_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.kf_id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('participant_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('diagnosis',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('age_at_event_days', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.kf_id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('sample',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('tissue_type', sa.Text(), nullable=True),
    sa.Column('composition', sa.Text(), nullable=True),
    sa.Column('anatomical_site', sa.Text(), nullable=True),
    sa.Column('age_at_event_days', sa.Integer(), nullable=True),
    sa.Column('tumor_descriptor', sa.Text(), nullable=True),
    sa.Column('participant_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.kf_id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('aliquot',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('shipment_origin', sa.Text(), nullable=True),
    sa.Column('shipment_destination', sa.Text(), nullable=True),
    sa.Column('analyte_type', sa.Text(), nullable=False),
    sa.Column('concentration', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('shipment_date', sa.DateTime(), nullable=True),
    sa.Column('sample_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.kf_id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('sequencing_experiment',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('experiment_date', sa.DateTime(), nullable=True),
    sa.Column('experiment_strategy', sa.Text(), nullable=False),
    sa.Column('center', sa.Text(), nullable=False),
    sa.Column('library_name', sa.Text(), nullable=True),
    sa.Column('library_strand', sa.Text(), nullable=True),
    sa.Column('is_paired_end', sa.Boolean(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('instrument_model', sa.Text(), nullable=True),
    sa.Column('max_insert_size', sa.Integer(), nullable=True),
    sa.Column('mean_insert_size', sa.Float(), nullable=True),
    sa.Column('mean_depth', sa.Float(), nullable=True),
    sa.Column('total_reads', sa.Integer(), nullable=True),
    sa.Column('mean_read_length', sa.Float(), nullable=True),
    sa.Column('aliquot_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['aliquot_id'], ['aliquot.kf_id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('genomic_file',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_type', sa.Text(), nullable=True),
    sa.Column('file_format', sa.Text(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('md5sum', sa.String(length=36), nullable=True),
    sa.Column('sequencing_experiment_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['sequencing_experiment_id'], ['sequencing_experiment.kf_id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('md5sum'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genomic_file')
    op.drop_table('sequencing_experiment')
    op.drop_table('aliquot')
    op.drop_table('sample')
    op.drop_table('diagnosis')
    op.drop_table('demographic')
    op.drop_table('participant')
    # ### end Alembic commands ###
