"""Change 'Homo Sapiens' to 'Homo sapiens'

Revision ID: 12850dab14e9
Revises: 025cf1ee0adf
Create Date: 2021-05-10 14:46:27.858830

"""
from sqlalchemy.sql import table, column
from sqlalchemy import String
from alembic import op


# revision identifiers, used by Alembic.
revision = '12850dab14e9'
down_revision = '025cf1ee0adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    participant = table('participant', column('species', String))

    connection.execute(
        participant.update().where(
            participant.c.species == 'Homo Sapiens'
        ).values(species='Homo sapiens')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    participant = table('participant', column('species', String))

    connection.execute(
        participant.update().where(
            participant.c.species == 'Homo sapiens'
        ).values(species='Homo Sapiens')
    )
    # ### end Alembic commands ###
