"""
1.19.0 Add parent_study_id to Study table

Revision ID: 1dd6c503d77f
Revises: 37449dd948c3
Create Date: 2024-04-09 10:38:20.889693

"""
from alembic import op
import sqlalchemy as sa

from dataservice.api.common.model import KfId

# revision identifiers, used by Alembic.
revision = '1dd6c503d77f'
down_revision = '37449dd948c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('parent_study_id',
                  KfId(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'parent_study_id')
    # ### end Alembic commands ###
