"""
Add diagnosis_category, tumor_location to Diagnosis entity

Revision ID: 2065a5e939dd
Revises: c60110f2a43a
Create Date: 2018-02-19 10:44:53.989900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2065a5e939dd'
down_revision = 'c60110f2a43a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis', sa.Column('diagnosis_category', sa.Text(), nullable=True))
    op.add_column('diagnosis', sa.Column('tumor_location', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnosis', 'tumor_location')
    op.drop_column('diagnosis', 'diagnosis_category')
    # ### end Alembic commands ###
