"""
Remove columns redundant with indexd files

Revision ID: 243980a97e4c
Revises: 04c620f9f768
Create Date: 2018-04-12 13:26:07.858007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '243980a97e4c'
down_revision = 'e3ee14b87b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_file', sa.Column('latest_did', postgresql.UUID(), nullable=False))
    op.drop_constraint('genomic_file_md5sum_key', 'genomic_file', type_='unique')
    op.drop_column('genomic_file', 'file_url')
    op.drop_column('genomic_file', 'file_size')
    op.drop_column('genomic_file', 'md5sum')
    op.drop_column('genomic_file', 'file_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_file', sa.Column('file_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('genomic_file', sa.Column('md5sum', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('genomic_file', sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('genomic_file', sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_unique_constraint('genomic_file_md5sum_key', 'genomic_file', ['md5sum'])
    op.drop_column('genomic_file', 'latest_did')
    # ### end Alembic commands ###
