"""
1.16.0 Add biospecimen.preservation_method

Revision ID: 3b427603af51
Revises: 16e588cc6b85
Create Date: 2023-12-08 15:03:02.945360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b427603af51'
down_revision = '16e588cc6b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biospecimen', sa.Column(
        'preservation_method', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biospecimen', 'preservation_method')
    # ### end Alembic commands ###
