"""
1.27.0 add vbr fields

Revision ID: 3c392765f4e0
Revises: 9f5a6dbfec37
Create Date: 2024-09-06 17:20:45.069931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c392765f4e0'
down_revision = '9f5a6dbfec37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biospecimen', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('biospecimen', sa.Column('amount_units', sa.Text(), nullable=True))
    op.add_column('sample', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('sample', sa.Column('amount_units', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'amount_units')
    op.drop_column('sample', 'amount')
    op.drop_column('biospecimen', 'amount_units')
    op.drop_column('biospecimen', 'amount')
    # ### end Alembic commands ###
