"""
Add consent_type, family_id, is_proband fields to participant

Revision ID: 44b3990e821e
Revises: 7ef81ce1ca05
Create Date: 2018-02-16 14:51:04.407767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44b3990e821e'
down_revision = '7ef81ce1ca05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('consent_type', sa.Text(), nullable=True))
    op.add_column('participant', sa.Column('family_id', sa.Text(), nullable=True))
    op.add_column('participant', sa.Column('is_proband', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'is_proband')
    op.drop_column('participant', 'family_id')
    op.drop_column('participant', 'consent_type')
    # ### end Alembic commands ###
