"""
Add new seq experiment fields and biospecimen.cell_entity

Revision ID: 59c19de6ba0b
Revises: 3c392765f4e0
Create Date: 2025-06-03 15:17:33.751285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c19de6ba0b'
down_revision = '3c392765f4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biospecimen', sa.Column('cell_entity', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('acquisition_type', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('cdna_read', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('cdna_read_offset', sa.Integer(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('cell_barcode_offset', sa.Integer(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('cell_barcode_read', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('cell_barcode_size', sa.Integer(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('chromatography_approach', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('end_bias', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('enrichment_approach', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('fraction_number', sa.Integer(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('fractionation_approach', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('ion_fragmentation', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('library_construction', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('mass_spec_rawfile_conversion', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('proteomics_experiment', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('quantification_label_id', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('quantification_labeling_method', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('quantification_technique', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('sequencing_mode', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('target_cell_number', sa.Integer(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('umi_barcode_offset', sa.Integer(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('umi_barcode_read', sa.Text(), nullable=True))
    op.add_column('sequencing_experiment', sa.Column('umi_barcode_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sequencing_experiment', 'umi_barcode_size')
    op.drop_column('sequencing_experiment', 'umi_barcode_read')
    op.drop_column('sequencing_experiment', 'umi_barcode_offset')
    op.drop_column('sequencing_experiment', 'target_cell_number')
    op.drop_column('sequencing_experiment', 'sequencing_mode')
    op.drop_column('sequencing_experiment', 'quantification_technique')
    op.drop_column('sequencing_experiment', 'quantification_labeling_method')
    op.drop_column('sequencing_experiment', 'quantification_label_id')
    op.drop_column('sequencing_experiment', 'proteomics_experiment')
    op.drop_column('sequencing_experiment', 'mass_spec_rawfile_conversion')
    op.drop_column('sequencing_experiment', 'library_construction')
    op.drop_column('sequencing_experiment', 'ion_fragmentation')
    op.drop_column('sequencing_experiment', 'fractionation_approach')
    op.drop_column('sequencing_experiment', 'fraction_number')
    op.drop_column('sequencing_experiment', 'enrichment_approach')
    op.drop_column('sequencing_experiment', 'end_bias')
    op.drop_column('sequencing_experiment', 'chromatography_approach')
    op.drop_column('sequencing_experiment', 'cell_barcode_size')
    op.drop_column('sequencing_experiment', 'cell_barcode_read')
    op.drop_column('sequencing_experiment', 'cell_barcode_offset')
    op.drop_column('sequencing_experiment', 'cdna_read_offset')
    op.drop_column('sequencing_experiment', 'cdna_read')
    op.drop_column('sequencing_experiment', 'acquisition_type')
    op.drop_column('biospecimen', 'cell_entity')
    # ### end Alembic commands ###
