"""
1.1.1 - Add relationship between diagnosis and biospecimen

Revision ID: 5b903b00dce4
Revises: dbe23598a508
Create Date: 2018-06-22 11:06:14.038532

"""
from alembic import op
import sqlalchemy as sa
import dataservice

# revision identifiers, used by Alembic.
revision = '5b903b00dce4'
down_revision = 'dbe23598a508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis', sa.Column(
        'biospecimen_id',
        dataservice.api.common.model.KfId(length=11), nullable=True))
    op.create_foreign_key(None, 'diagnosis', 'biospecimen',
                          ['biospecimen_id'], ['kf_id'])
    op.drop_constraint('read_group_genomic_file_id_fkey', 'read_group',
                       type_='foreignkey')
    op.create_foreign_key(None, 'read_group', 'genomic_file', [
                          'genomic_file_id'], ['kf_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'read_group', type_='foreignkey')
    op.create_foreign_key('read_group_genomic_file_id_fkey', 'read_group',
                          'genomic_file', ['genomic_file_id'], ['kf_id'])
    op.drop_constraint(None, 'diagnosis', type_='foreignkey')
    op.drop_column('diagnosis', 'biospecimen_id')
    # ### end Alembic commands ###
