"""
Add Investigator table to Data Model

Revision ID: 5c0f57d4f559
Revises: 2065a5e939dd
Create Date: 2018-02-20 22:33:36.763014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c0f57d4f559'
down_revision = '2065a5e939dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigator',
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('institution', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('kf_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    op.add_column('study', sa.Column('investigator_id', sa.String(length=8), nullable=True))
    op.create_foreign_key(None, 'study', 'investigator', ['investigator_id'], ['kf_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study', type_='foreignkey')
    op.drop_column('study', 'investigator_id')
    op.drop_table('investigator')
    # ### end Alembic commands ###
