"""
Add short_name to study
Rename phenotype to source_text_phenotype

Revision ID: 5c8919540598
Revises: 243980a97e4c
Create Date: 2018-04-23 11:46:29.384980

"""
from alembic import op
import sqlalchemy as sa
import dataservice

# revision identifiers, used by Alembic.
revision = '5c8919540598'
down_revision = '243980a97e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phenotype', sa.Column('source_text_phenotype', sa.Text(), nullable=True))
    op.drop_column('phenotype', 'phenotype')
    op.add_column('study', sa.Column('short_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'short_name')
    op.add_column('phenotype', sa.Column('phenotype', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('phenotype', 'source_text_phenotype')
    # ### end Alembic commands ###
