"""
Add cavatica_task, cavatica_app, cavatica_task_genomic_file tables
Remove workflow and workflow_genomic_file tables

Revision ID: 64d316354133
Revises: 669514359df5
Create Date: 2018-05-04 17:10:44.651532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64d316354133'
down_revision = '669514359df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cavatica_app',
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('external_cavatica_app_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('github_commit_url', sa.Text(), nullable=True),
    sa.Column('kf_id', dataservice.api.common.model.KfId(length=11), nullable=False),
    sa.PrimaryKeyConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('cavatica_task',
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('external_cavatica_task_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('cavatica_app_id', dataservice.api.common.model.KfId(length=11), nullable=True),
    sa.Column('kf_id', dataservice.api.common.model.KfId(length=11), nullable=False),
    sa.ForeignKeyConstraint(['cavatica_app_id'], ['cavatica_app.kf_id'], ),
    sa.PrimaryKeyConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('cavatica_task_genomic_file',
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('genomic_file_id', dataservice.api.common.model.KfId(length=11), nullable=False),
    sa.Column('cavatica_task_id', dataservice.api.common.model.KfId(length=11), nullable=False),
    sa.Column('is_input', sa.Boolean(), nullable=False),
    sa.Column('kf_id', dataservice.api.common.model.KfId(length=11), nullable=False),
    sa.ForeignKeyConstraint(['cavatica_task_id'], ['cavatica_task.kf_id'], ),
    sa.ForeignKeyConstraint(['genomic_file_id'], ['genomic_file.kf_id'], ),
    sa.PrimaryKeyConstraint('kf_id'),
    sa.UniqueConstraint('genomic_file_id', 'cavatica_task_id', 'is_input'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('workflow')
    op.drop_table('workflow_genomic_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_genomic_file',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('genomic_file_id', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('workflow_id', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('is_input', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('kf_id', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genomic_file_id'], ['genomic_file.kf_id'], name='workflow_genomic_file_genomic_file_id_fkey'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.kf_id'], name='workflow_genomic_file_workflow_id_fkey'),
    sa.PrimaryKeyConstraint('kf_id', name='workflow_genomic_file_pkey'),
    sa.UniqueConstraint('genomic_file_id', 'workflow_id', 'is_input', name='workflow_genomic_file_genomic_file_id_workflow_id_is_input_key'),
    sa.UniqueConstraint('uuid', name='workflow_genomic_file_uuid_key')
    )
    op.create_table('workflow',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('github_commit_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kf_id', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('kf_id', name='workflow_pkey'),
    sa.UniqueConstraint('uuid', name='workflow_uuid_key')
    )
    op.drop_table('cavatica_task_genomic_file')
    op.drop_table('cavatica_task')
    op.drop_table('cavatica_app')
    # ### end Alembic commands ###
