"""
Drop null constraint on biospecimen_id

Revision ID: 669514359df5
Revises: 7d7df8d524f7
Create Date: 2018-05-03 15:46:31.716543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669514359df5'
down_revision = '7d7df8d524f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('genomic_file', 'biospecimen_id',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('genomic_file', 'biospecimen_id',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###
