"""
Create Phenotype table

Revision ID: 6b2810b12ce7
Revises: ed76240485bc
Create Date: 2018-02-13 15:17:09.918264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2810b12ce7'
down_revision = 'ed76240485bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phenotype',
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('phenotype', sa.Text(), nullable=True),
    sa.Column('hpo_id', sa.Text(), nullable=True),
    sa.Column('observed', sa.Text(), nullable=True),
    sa.Column('age_at_event_days', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.kf_id'], ),
    sa.PrimaryKeyConstraint('kf_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phenotype')
    # ### end Alembic commands ###
