""" 
Add file_size to genomic_file table

Revision ID: 6bee334483a5
Revises: 9c4a87f00784
Create Date: 2018-02-26 17:07:12.852222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bee334483a5'
down_revision = '9c4a87f00784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_file', sa.Column('file_size', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genomic_file', 'file_size')
    # ### end Alembic commands ###
