"""
Add icd_id, uberon_id, snomed_id to diagnosis
Add release_status to study
Add reference_genome, is_harmonized to genomic_file

Revision ID: 6c5b80679ee3
Revises: a10ebb4c43c7
Create Date: 2018-04-06 10:56:27.865173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5b80679ee3'
down_revision = 'a10ebb4c43c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis', sa.Column('icd_id', sa.Text(), nullable=True))
    op.add_column('diagnosis', sa.Column('mondo_id', sa.Text(), nullable=True))
    op.add_column('diagnosis', sa.Column('uberon_id', sa.Text(), nullable=True))
    op.add_column('genomic_file', sa.Column('is_harmonized', sa.Boolean(), nullable=True))
    op.add_column('genomic_file', sa.Column('reference_genome', sa.Text(), nullable=True))
    op.add_column('phenotype', sa.Column('snomed_id', sa.Text(), nullable=True))
    op.add_column('study', sa.Column('release_status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'release_status')
    op.drop_column('phenotype', 'snomed_id')
    op.drop_column('genomic_file', 'reference_genome')
    op.drop_column('genomic_file', 'is_harmonized')
    op.drop_column('diagnosis', 'uberon_id')
    op.drop_column('diagnosis', 'mondo_id')
    op.drop_column('diagnosis', 'icd_id')
    # ### end Alembic commands ###
