"""
Add availability to study_file

Revision ID: 719d457de080
Revises: d9ba1b15d196
Create Date: 2018-04-26 11:31:36.052761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719d457de080'
down_revision = 'd9ba1b15d196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_file', sa.Column(
        'availability', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_file', 'availability')
    # ### end Alembic commands ###
