"""
Update sequencing_experiment_id to be nullable in genomic_file


Revision ID: 7d7df8d524f7
Revises: 719d457de080
Create Date: 2018-05-01 17:27:12.371259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7df8d524f7'
down_revision = '719d457de080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('genomic_file', 'sequencing_experiment_id',
                    existing_type=sa.VARCHAR(length=11),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('genomic_file', 'sequencing_experiment_id',
                    existing_type=sa.VARCHAR(length=11),
                    nullable=False)
    # ### end Alembic commands ###
