"""
1.6.0 - Move sequencing statistics to genomic_file

Revision ID: 7d98a2835505
Revises: 5f3a7baa3fda
Create Date: 2018-11-16 11:11:52.408375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime
import dataservice
from dataservice.api.common.id_service import uuid_generator, kf_id_generator

# revision identifiers, used by Alembic.
revision = '7d98a2835505'
down_revision = '5f3a7baa3fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_file', sa.Column('max_insert_size', sa.Integer(), nullable=True))
    op.add_column('genomic_file', sa.Column('mean_depth', sa.Float(), nullable=True))
    op.add_column('genomic_file', sa.Column('mean_insert_size', sa.Float(), nullable=True))
    op.add_column('genomic_file', sa.Column('mean_read_length', sa.Float(), nullable=True))
    op.add_column('genomic_file', sa.Column('total_reads', sa.Integer(), nullable=True))

    t_se = sa.Table(
        'sequencing_experiment',
        sa.MetaData(),
        sa.Column('kf_id', dataservice.api.common.model.KfId(length=11), nullable=False),
        sa.Column('max_insert_size', sa.Integer(), nullable=True),
        sa.Column('mean_depth', sa.Float(), nullable=True),
        sa.Column('mean_insert_size', sa.Float(), nullable=True),
        sa.Column('mean_read_length', sa.Float(), nullable=True),
        sa.Column('total_reads', sa.Integer(), nullable=True)
    )

    t_gf = sa.Table(
        'genomic_file',
        sa.MetaData(),
        sa.Column('kf_id', dataservice.api.common.model.KfId(length=11), nullable=False),
        sa.Column('sequencing_experiment_id', dataservice.api.common.model.KfId(length=11), nullable=False),
        sa.ForeignKeyConstraint(['sequencing_experiment_id'], [
            'sequencing_experiment.kf_id'], ),
        sa.Column('max_insert_size', sa.Integer(), nullable=True),
        sa.Column('mean_depth', sa.Float(), nullable=True),
        sa.Column('mean_insert_size', sa.Float(), nullable=True),
        sa.Column('mean_read_length', sa.Float(), nullable=True),
        sa.Column('total_reads', sa.Integer(), nullable=True)
    )

    connection = op.get_bind()

    # We are going to move fields from sequencing experiment to the above cols
    results = connection.execute(sa.select([
        t_se.c.kf_id,
        t_se.c.max_insert_size,
        t_se.c.mean_depth,
        t_se.c.mean_insert_size,
        t_se.c.mean_read_length,
        t_se.c.total_reads
    ])).fetchall()

    for r in results:
        connection.execute(t_gf.update().where(t_gf.c.sequencing_experiment_id==r[0]).values(
                max_insert_size=r[1],
                mean_depth=r[2],
                mean_insert_size=r[3],
                mean_read_length=r[4],
                total_reads=r[5]
            ))

    op.drop_column('sequencing_experiment', 'mean_read_length')
    op.drop_column('sequencing_experiment', 'max_insert_size')
    op.drop_column('sequencing_experiment', 'mean_insert_size')
    op.drop_column('sequencing_experiment', 'total_reads')
    op.drop_column('sequencing_experiment', 'mean_depth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequencing_experiment', sa.Column('mean_depth', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sequencing_experiment', sa.Column('total_reads', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sequencing_experiment', sa.Column('mean_insert_size', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sequencing_experiment', sa.Column('max_insert_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sequencing_experiment', sa.Column('mean_read_length', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('genomic_file', 'total_reads')
    op.drop_column('genomic_file', 'mean_read_length')
    op.drop_column('genomic_file', 'mean_insert_size')
    op.drop_column('genomic_file', 'mean_depth')
    op.drop_column('genomic_file', 'max_insert_size')
    # ### end Alembic commands ###
