"""
Add workflow and workflow_genomic_file tables

Revision ID: 7ef81ce1ca05
Revises: c23f9043d57b
Create Date: 2018-02-16 13:43:05.992093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef81ce1ca05'
down_revision = 'c23f9043d57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('github_commit_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('kf_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('workflow_genomic_file',
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('genomic_file_id', sa.String(length=8), nullable=False),
    sa.Column('workflow_id', sa.String(length=8), nullable=False),
    sa.Column('is_input', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['genomic_file_id'], ['genomic_file.kf_id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.kf_id'], ),
    sa.PrimaryKeyConstraint('kf_id'),
    sa.UniqueConstraint('genomic_file_id', 'workflow_id', 'is_input'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_genomic_file')
    op.drop_table('workflow')
    # ### end Alembic commands ###
