"""
1.25.0 Add cavatica gf fields

Revision ID: 869f891d97ad
Revises: 0454317cd224
Create Date: 2024-09-04 14:48:36.499552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869f891d97ad'
down_revision = '0454317cd224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_file', sa.Column('cavatica_file_id', sa.Text(), nullable=True))
    op.add_column('genomic_file', sa.Column('cavatica_volume', sa.Text(), nullable=True))
    op.add_column('genomic_file', sa.Column('workflow_endpoint', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genomic_file', 'workflow_endpoint')
    op.drop_column('genomic_file', 'cavatica_volume')
    op.drop_column('genomic_file', 'cavatica_file_id')
    # ### end Alembic commands ###
