"""empty message

Revision ID: 99a46e736497
Revises: dda74cdf687d
Create Date: 2018-03-30 15:38:27.615254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a46e736497'
down_revision = 'dda74cdf687d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('uberon', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'uberon')
    # ### end Alembic commands ###
