"""
1.2.2 - Add affected_status, diagnosis_category and update is_proband
to nullable for participant
Add family_type to family
Add source_text_notes to family_relationship

Revision ID: 9d1b39dd9af5
Revises: c0f56e327e8d
Create Date: 2018-08-09 12:11:13.261674

"""
from alembic import op
import sqlalchemy as sa
import dataservice

# revision identifiers, used by Alembic.
revision = '9d1b39dd9af5'
down_revision = 'c0f56e327e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family', sa.Column('family_type', sa.Text(), nullable=True))
    op.add_column('family_relationship', sa.Column(
        'source_text_notes', sa.Text(), nullable=True))
    op.add_column('participant', sa.Column(
        'affected_status', sa.Boolean(), nullable=True))
    op.add_column('participant', sa.Column(
        'diagnosis_category', sa.Text(), nullable=True))
    op.alter_column('participant', 'is_proband',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant', 'is_proband',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.drop_column('participant', 'diagnosis_category')
    op.drop_column('participant', 'affected_status')
    op.drop_column('family_relationship', 'source_text_notes')
    op.drop_column('family', 'family_type')
    # ### end Alembic commands ###
