"""
Add outcome entity to database

Revision ID: 9dd3479c9015
Revises: b7852f8aab0a
Create Date: 2018-02-13 14:23:58.021013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd3479c9015'
down_revision = 'b7852f8aab0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outcome',
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('vital_status', sa.Text(), nullable=True),
    sa.Column('disease_related', sa.Text(), nullable=True),
    sa.Column('age_at_event_days', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.kf_id'], ),
    sa.PrimaryKeyConstraint('kf_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcome')
    # ### end Alembic commands ###
