"""
Change to pg UUID type for uuid fields

Revision ID: 9ff025c8ba49
Revises: 44b3990e821e
Create Date: 2018-02-17 09:35:18.574246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ff025c8ba49'
down_revision = '44b3990e821e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tbls = ['aliquot', 'demographic', 'diagnosis', 'genomic_file', 'outcome',
            'participant', 'phenotype', 'sample', 'sequencing_experiment',
            'study']
    for tbl in tbls:
        op.execute('ALTER TABLE {} ALTER COLUMN uuid '.format(tbl) +
                   'TYPE UUID USING uuid::uuid')

    op.execute('ALTER TABLE genomic_file ALTER COLUMN md5sum ' +
               'TYPE UUID USING md5sum::uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study', 'uuid',
               existing_type=postgresql.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('sequencing_experiment', 'uuid',
               existing_type=postgresql.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('sample', 'uuid',
               existing_type=postgresql.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('phenotype', 'uuid',
               existing_type=postgresql.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('participant', 'uuid',
               existing_type=postgresql.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('outcome', 'uuid',
               existing_type=postgresql.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('genomic_file', 'uuid',
               existing_type=postgresql.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('genomic_file', 'md5sum',
               existing_type=postgresql.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('diagnosis', 'uuid',
               existing_type=postgresql.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('demographic', 'uuid',
               existing_type=postgresql.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('aliquot', 'uuid',
               existing_type=postgresql.UUID(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###
