"""
Add family model

Revision ID: a10ebb4c43c7
Revises: b2aab064a0b6
Create Date: 2018-04-04 16:02:43.132088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import dataservice

# revision identifiers, used by Alembic.
revision = 'a10ebb4c43c7'
down_revision = 'b2aab064a0b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('kf_id', dataservice.api.common.model.KfId(length=11), nullable=False),
    sa.PrimaryKeyConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_foreign_key(None, 'participant', 'family', ['family_id'], ['kf_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_table('family')
    # ### end Alembic commands ###
