"""
Add study_file table

Revision ID: a421e4e2710a
Revises: 5c0f57d4f559
Create Date: 2018-02-21 12:22:00.543956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a421e4e2710a'
down_revision = '5c0f57d4f559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_file',
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('study_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['study.kf_id'], ),
    sa.PrimaryKeyConstraint('kf_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_file')
    # ### end Alembic commands ###
