"""
1.21.0 Add new SampleRelationship table

Revision ID: a67246728831
Revises: d639938c6066
Create Date: 2024-05-15 13:47:54.036394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import dataservice

# revision identifiers, used by Alembic.
revision = 'a67246728831'
down_revision = 'd639938c6066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_relationship',
                    sa.Column('uuid', postgresql.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(), nullable=True),
                    sa.Column('visible', sa.Boolean(),
                              server_default='true', nullable=False),
                    sa.Column('visibility_reason', sa.Text(), nullable=True),
                    sa.Column('visibility_comment', sa.Text(), nullable=True),
                    sa.Column('external_id', sa.Text(), nullable=True),
                    sa.Column('parent_id', dataservice.api.common.model.KfId(
                        length=11), nullable=False),
                    sa.Column('child_id', dataservice.api.common.model.KfId(
                        length=11), nullable=False),
                    sa.Column('external_parent_id', sa.Text(), nullable=True),
                    sa.Column('external_child_id', sa.Text(), nullable=True),
                    sa.Column('notes', sa.Text(), nullable=True),
                    sa.Column('kf_id', dataservice.api.common.model.KfId(
                        length=11), nullable=False),
                    sa.ForeignKeyConstraint(['child_id'], ['sample.kf_id'], ),
                    sa.ForeignKeyConstraint(['parent_id'], ['sample.kf_id'], ),
                    sa.PrimaryKeyConstraint('kf_id'),
                    sa.UniqueConstraint('child_id'),
                    sa.UniqueConstraint('uuid')
                    )
    op.create_index(op.f('ix_sample_relationship_created_at'),
                    'sample_relationship', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sample_relationship_created_at'),
                  table_name='sample_relationship')
    op.drop_table('sample_relationship')
    # ### end Alembic commands ###
