"""
Remove unique constraint from kf_id

Revision ID: aafa70610916
Revises: 7ef81ce1ca05
Create Date: 2018-02-16 14:51:16.933259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aafa70610916'
down_revision = '7ef81ce1ca05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('aliquot_kf_id_key', 'aliquot', type_='unique')
    op.drop_constraint('demographic_kf_id_key', 'demographic', type_='unique')
    op.drop_constraint('diagnosis_kf_id_key', 'diagnosis', type_='unique')
    op.drop_constraint('genomic_file_kf_id_key', 'genomic_file', type_='unique')
    op.drop_constraint('participant_kf_id_key', 'participant', type_='unique')
    op.drop_constraint('phenotype_kf_id_key', 'phenotype', type_='unique')
    op.drop_constraint('sample_kf_id_key', 'sample', type_='unique')
    op.drop_constraint('sequencing_experiment_kf_id_key', 'sequencing_experiment', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sequencing_experiment_kf_id_key', 'sequencing_experiment', ['kf_id'])
    op.create_unique_constraint('sample_kf_id_key', 'sample', ['kf_id'])
    op.create_unique_constraint('phenotype_kf_id_key', 'phenotype', ['kf_id'])
    op.create_unique_constraint('participant_kf_id_key', 'participant', ['kf_id'])
    op.create_unique_constraint('genomic_file_kf_id_key', 'genomic_file', ['kf_id'])
    op.create_unique_constraint('diagnosis_kf_id_key', 'diagnosis', ['kf_id'])
    op.create_unique_constraint('demographic_kf_id_key', 'demographic', ['kf_id'])
    op.create_unique_constraint('aliquot_kf_id_key', 'aliquot', ['kf_id'])
    # ### end Alembic commands ###
