"""
Merge participant and demographic tables

Revision ID: b2aab064a0b6
Revises: 6bee334483a5
Create Date: 2018-04-02 17:30:46.256830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2aab064a0b6'
down_revision = '6bee334483a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demographic')
    op.add_column('participant', sa.Column('ethnicity', sa.Text(), nullable=True))
    op.add_column('participant', sa.Column('gender', sa.Text(), nullable=True))
    op.add_column('participant', sa.Column('race', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'race')
    op.drop_column('participant', 'gender')
    op.drop_column('participant', 'ethnicity')
    op.create_table('demographic',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('race', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ethnicity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('participant_id', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('kf_id', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.kf_id'], name='demographic_participant_id_fkey'),
    sa.PrimaryKeyConstraint('kf_id', name='demographic_pkey'),
    sa.UniqueConstraint('participant_id', name='demographic_participant_id_key'),
    sa.UniqueConstraint('uuid', name='demographic_uuid_key')
    )
    # ### end Alembic commands ###
