"""
Drop autoincrement _id column and use kf_id the primary key

Revision ID: b7852f8aab0a
Revises: 0cc35a21afc2
Create Date: 2018-02-07 19:25:40.035962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7852f8aab0a'
down_revision = '0cc35a21afc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aliquot', '_id')
    op.drop_column('demographic', '_id')
    op.drop_column('diagnosis', '_id')
    op.drop_column('genomic_file', '_id')
    op.drop_column('participant', '_id')
    op.drop_column('sample', '_id')
    op.drop_column('sequencing_experiment', '_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sequencing_experiment', sa.Column('_id', sa.INTEGER(), nullable=False))
    op.add_column('sample', sa.Column('_id', sa.INTEGER(), server_default=sa.text("nextval('sample__id_seq'::regclass)"), nullable=False))
    op.add_column('participant', sa.Column('_id', sa.INTEGER(), nullable=False))
    op.add_column('genomic_file', sa.Column('_id', sa.INTEGER(), nullable=False))
    op.add_column('diagnosis', sa.Column('_id', sa.INTEGER(), nullable=False))
    op.add_column('demographic', sa.Column('_id', sa.INTEGER(), nullable=False))
    op.add_column('aliquot', sa.Column('_id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
