"""
1.2.1 - Add visible field to base model

Revision ID: c0f56e327e8d
Revises: 088f00b10226
Create Date: 2018-08-07 11:12:04.060987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f56e327e8d'
down_revision = '088f00b10226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alias_group', sa.Column(
        'visible', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('biospecimen', sa.Column(
        'visible', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('biospecimen_genomic_file', sa.Column(
        'visible', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('cavatica_app', sa.Column(
        'visible', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('cavatica_task', sa.Column(
        'visible', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('cavatica_task_genomic_file', sa.Column(
        'visible', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('diagnosis', sa.Column('visible', sa.Boolean(),
                                         server_default='true', nullable=False))
    op.add_column('family', sa.Column('visible', sa.Boolean(),
                                      server_default='true', nullable=False))
    op.add_column('family_relationship', sa.Column(
        'visible', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('genomic_file', sa.Column(
        'visible', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('investigator', sa.Column(
        'visible', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('outcome', sa.Column('visible', sa.Boolean(),
                                       server_default='true', nullable=False))
    op.add_column('participant', sa.Column(
        'visible', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('phenotype', sa.Column('visible', sa.Boolean(),
                                         server_default='true', nullable=False))
    op.add_column('read_group', sa.Column('visible', sa.Boolean(),
                                          server_default='true', nullable=False))
    op.add_column('sequencing_center', sa.Column(
        'visible', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('sequencing_experiment', sa.Column(
        'visible', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('study', sa.Column('visible', sa.Boolean(),
                                     server_default='true', nullable=False))
    op.add_column('study_file', sa.Column('visible', sa.Boolean(),
                                          server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_file', 'visible')
    op.drop_column('study', 'visible')
    op.drop_column('sequencing_experiment', 'visible')
    op.drop_column('sequencing_center', 'visible')
    op.drop_column('read_group', 'visible')
    op.drop_column('phenotype', 'visible')
    op.drop_column('participant', 'visible')
    op.drop_column('outcome', 'visible')
    op.drop_column('investigator', 'visible')
    op.drop_column('genomic_file', 'visible')
    op.drop_column('family_relationship', 'visible')
    op.drop_column('family', 'visible')
    op.drop_column('diagnosis', 'visible')
    op.drop_column('cavatica_task_genomic_file', 'visible')
    op.drop_column('cavatica_task', 'visible')
    op.drop_column('cavatica_app', 'visible')
    op.drop_column('biospecimen_genomic_file', 'visible')
    op.drop_column('biospecimen', 'visible')
    op.drop_column('alias_group', 'visible')
    # ### end Alembic commands ###
