"""
Add study table and relation to participant table

Revision ID: c23f9043d57b
Revises: c1b8fdd17637
Create Date: 2018-02-15 15:59:52.966094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23f9043d57b'
down_revision = 'c1b8fdd17637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study',
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('data_access_authority', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('kf_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_unique_constraint(None, 'outcome', ['kf_id'])
    op.add_column('participant', sa.Column('study_id', sa.String(length=8), nullable=False))
    op.create_foreign_key(None, 'participant', 'study', ['study_id'], ['kf_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_column('participant', 'study_id')
    op.drop_constraint(None, 'outcome', type_='unique')
    op.drop_table('study')
    # ### end Alembic commands ###
