"""
1.23.0 Allow parent or child sample in sample relationship to be null

This allows us to enter a row where the parent is null and child is not which
represents a root of a sample tree

Validation ensures that you cannot enter a sample relationship where both
the parent and child sample in the relationship are null

Revision ID: c2f77debb22d
Revises: f07d043290d0
Create Date: 2024-06-11 13:05:50.923693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f77debb22d'
down_revision = 'f07d043290d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample_relationship', 'child_id',
                    existing_type=sa.VARCHAR(length=11),
                    nullable=True)
    op.alter_column('sample_relationship', 'parent_id',
                    existing_type=sa.VARCHAR(length=11),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample_relationship', 'parent_id',
                    existing_type=sa.VARCHAR(length=11),
                    nullable=False)
    op.alter_column('sample_relationship', 'child_id',
                    existing_type=sa.VARCHAR(length=11),
                    nullable=False)
    # ### end Alembic commands ###
