"""
1.4.3 - Add external_id col to biospecimen_diagnosis and biospecimen_genomic_file

Revision ID: c89c99674f2c
Revises: 7f0b46d388a1
Create Date: 2018-10-10 12:12:04.826654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89c99674f2c'
down_revision = '7f0b46d388a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biospecimen_diagnosis', sa.Column('external_id', sa.Text(), nullable=True))
    op.add_column('biospecimen_genomic_file', sa.Column('external_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biospecimen_genomic_file', 'external_id')
    op.drop_column('biospecimen_diagnosis', 'external_id')
    # ### end Alembic commands ###
