"""
1.3.1 - Rename biospecimen table column volume_ml to volume_ul

Revision ID: cdbd609e2bd5
Revises: ce01ada6ac80
Create Date: 2018-08-27 10:28:59.687358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import dataservice

# revision identifiers, used by Alembic.
revision = 'cdbd609e2bd5'
down_revision = 'ce01ada6ac80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('biospecimen', 'volume_ml', new_column_name='volume_ul')
    op.add_column('biospecimen_diagnosis', sa.Column(
        'visible', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biospecimen_diagnosis', 'visible')
    op.alter_column('biospecimen', 'volume_ul', new_column_name='volume_ml')
    # ### end Alembic commands ###
