"""
1.3.0 - Add biospecimen_diagnosis association table

Revision ID: ce01ada6ac80
Revises: 088f00b10226
Create Date: 2018-07-25 11:55:35.583312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import dataservice

# revision identifiers, used by Alembic.
revision = 'ce01ada6ac80'
down_revision = '088f00b10226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biospecimen_diagnosis',
                    sa.Column('uuid', postgresql.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(), nullable=True),
                    sa.Column('diagnosis_id', dataservice.api.common.model.KfId(
                        length=11), nullable=False),
                    sa.Column('biospecimen_id', dataservice.api.common.model.KfId(
                        length=11), nullable=False),
                    sa.Column('kf_id', dataservice.api.common.model.KfId(
                        length=11), nullable=False),
                    sa.ForeignKeyConstraint(['biospecimen_id'], [
                                            'biospecimen.kf_id'], ),
                    sa.ForeignKeyConstraint(
                        ['diagnosis_id'], ['diagnosis.kf_id'], ),
                    sa.PrimaryKeyConstraint('kf_id'),
                    sa.UniqueConstraint('diagnosis_id', 'biospecimen_id'),
                    sa.UniqueConstraint('uuid')
                    )
    op.drop_constraint('diagnosis_biospecimen_id_fkey',
                       'diagnosis', type_='foreignkey')
    op.drop_column('diagnosis', 'biospecimen_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis', sa.Column('biospecimen_id', sa.VARCHAR(
        length=11), autoincrement=False, nullable=True))
    op.create_foreign_key('diagnosis_biospecimen_id_fkey',
                          'diagnosis', 'biospecimen', ['biospecimen_id'], ['kf_id'])
    op.drop_table('biospecimen_diagnosis')
    # ### end Alembic commands ###
