"""
1.4.2 - Add external_id field to read_group_genomic_file.
Useful for debugging and tracking entities during data ingest.

Revision ID: d107dfcba1c1
Revises: 7f0b46d388a1
Create Date: 2018-10-09 13:23:20.548246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd107dfcba1c1'
down_revision = '7f0b46d388a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('read_group_genomic_file', sa.Column('external_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('read_group_genomic_file', 'external_id')
    # ### end Alembic commands ###
