"""
1.20.0 Add specimen_status to Biospecimen

Revision ID: d639938c6066
Revises: 7cab6c9d8a24
Create Date: 2024-05-02 15:07:04.498316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd639938c6066'
down_revision = '7cab6c9d8a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biospecimen', sa.Column('specimen_status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biospecimen', 'specimen_status')
    # ### end Alembic commands ###
