"""
1.15.0 - Add indexd fields to Genomic File

Revision ID: d93282327435
Revises: 475214ed802d
Create Date: 2022-04-27 16:59:56.151412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd93282327435'
down_revision = '475214ed802d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_file', sa.Column('acl', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('genomic_file', sa.Column('file_name', sa.Text(), nullable=True))
    op.add_column('genomic_file', sa.Column('hashes', sa.JSON(), nullable=True))
    op.add_column('genomic_file', sa.Column('size', sa.BigInteger(), nullable=True))
    op.add_column('genomic_file', sa.Column('urls', sa.ARRAY(sa.Text()), nullable=True))
    op.alter_column('genomic_file', 'latest_did',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('genomic_file', 'latest_did',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_column('genomic_file', 'urls')
    op.drop_column('genomic_file', 'size')
    op.drop_column('genomic_file', 'hashes')
    op.drop_column('genomic_file', 'file_name')
    op.drop_column('genomic_file', 'acl')
    # ### end Alembic commands ###
