"""
Rename ontology_ids and add external_id's to missing entities

Revision ID: d9ba1b15d196
Revises: 83788dfcbd00
Create Date: 2018-04-25 16:26:19.227853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ba1b15d196'
down_revision = '83788dfcbd00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biospecimen', sa.Column('ncit_id_anatomical_site', sa.Text(), nullable=True))
    op.add_column('biospecimen', sa.Column('ncit_id_tissue_type', sa.Text(), nullable=True))
    op.add_column('biospecimen', sa.Column('source_text_anatomical_site', sa.Text(), nullable=True))
    op.add_column('biospecimen', sa.Column('source_text_tissue_type', sa.Text(), nullable=True))
    op.add_column('biospecimen', sa.Column('source_text_tumor_descriptor', sa.Text(), nullable=True))
    op.add_column('biospecimen', sa.Column('spatial_descriptor', sa.Text(), nullable=True))
    op.add_column('biospecimen', sa.Column('uberon_id_anatomical_site', sa.Text(), nullable=True))
    op.drop_column('biospecimen', 'tissue_type')
    op.drop_column('biospecimen', 'uberon_id')
    op.drop_column('biospecimen', 'tumor_descriptor')
    op.drop_column('biospecimen', 'anatomical_site')
    op.add_column('diagnosis', sa.Column('icd_id_diagnosis', sa.Text(), nullable=True))
    op.add_column('diagnosis', sa.Column('mondo_id_diagnosis', sa.Text(), nullable=True))
    op.add_column('diagnosis', sa.Column('ncit_id_diagnosis', sa.Text(), nullable=True))
    op.add_column('diagnosis', sa.Column('source_text_diagnosis', sa.Text(), nullable=True))
    op.add_column('diagnosis', sa.Column('source_text_tumor_location', sa.Text(), nullable=True))
    op.add_column('diagnosis', sa.Column('spatial_descriptor', sa.Text(), nullable=True))
    op.add_column('diagnosis', sa.Column('uberon_id_tumor_location', sa.Text(), nullable=True))
    op.drop_column('diagnosis', 'tumor_location')
    op.drop_column('diagnosis', 'diagnosis')
    op.drop_column('diagnosis', 'mondo_id')
    op.drop_column('diagnosis', 'icd_id')
    op.drop_column('diagnosis', 'uberon_id')
    op.add_column('family_relationship', sa.Column('external_id', sa.Text(), nullable=True))
    op.add_column('genomic_file', sa.Column('availability', sa.Text(), nullable=True))
    op.add_column('genomic_file', sa.Column('external_id', sa.Text(), nullable=True))
    op.add_column('investigator', sa.Column('external_id', sa.Text(), nullable=True))
    op.add_column('outcome', sa.Column('external_id', sa.Text(), nullable=True))
    op.add_column('phenotype', sa.Column('external_id', sa.Text(), nullable=True))
    op.add_column('phenotype', sa.Column('hpo_id_phenotype', sa.Text(), nullable=True))
    op.add_column('phenotype', sa.Column('snomed_id_phenotype', sa.Text(), nullable=True))
    op.add_column('phenotype', sa.Column('source_text_phenotype', sa.Text(), nullable=True))
    op.drop_column('phenotype', 'hpo_id')
    op.drop_column('phenotype', 'snomed_id')
    op.drop_column('phenotype', 'phenotype')
    op.add_column('sequencing_center', sa.Column('external_id', sa.Text(), nullable=True))
    op.add_column('study', sa.Column('short_name', sa.Text(), nullable=True))
    op.add_column('study_file', sa.Column('external_id', sa.Text(), nullable=True))
    op.add_column('workflow', sa.Column('external_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'external_id')
    op.drop_column('study_file', 'external_id')
    op.drop_column('study', 'short_name')
    op.drop_column('sequencing_center', 'external_id')
    op.add_column('phenotype', sa.Column('phenotype', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('phenotype', sa.Column('snomed_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('phenotype', sa.Column('hpo_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('phenotype', 'source_text_phenotype')
    op.drop_column('phenotype', 'snomed_id_phenotype')
    op.drop_column('phenotype', 'hpo_id_phenotype')
    op.drop_column('phenotype', 'external_id')
    op.drop_column('outcome', 'external_id')
    op.drop_column('investigator', 'external_id')
    op.drop_column('genomic_file', 'external_id')
    op.drop_column('genomic_file', 'availability')
    op.drop_column('family_relationship', 'external_id')
    op.add_column('diagnosis', sa.Column('uberon_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('diagnosis', sa.Column('icd_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('diagnosis', sa.Column('mondo_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('diagnosis', sa.Column('diagnosis', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('diagnosis', sa.Column('tumor_location', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('diagnosis', 'uberon_id_tumor_location')
    op.drop_column('diagnosis', 'spatial_descriptor')
    op.drop_column('diagnosis', 'source_text_tumor_location')
    op.drop_column('diagnosis', 'source_text_diagnosis')
    op.drop_column('diagnosis', 'ncit_id_diagnosis')
    op.drop_column('diagnosis', 'mondo_id_diagnosis')
    op.drop_column('diagnosis', 'icd_id_diagnosis')
    op.add_column('biospecimen', sa.Column('anatomical_site', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('biospecimen', sa.Column('tumor_descriptor', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('biospecimen', sa.Column('uberon_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('biospecimen', sa.Column('tissue_type', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('biospecimen', 'uberon_id_anatomical_site')
    op.drop_column('biospecimen', 'spatial_descriptor')
    op.drop_column('biospecimen', 'source_text_tumor_descriptor')
    op.drop_column('biospecimen', 'source_text_tissue_type')
    op.drop_column('biospecimen', 'source_text_anatomical_site')
    op.drop_column('biospecimen', 'ncit_id_tissue_type')
    op.drop_column('biospecimen', 'ncit_id_anatomical_site')
    # ### end Alembic commands ###
