"""
1.1.0 - Add Read Group model

Revision ID: dbe23598a508
Revises: 8f1ad897fb0f
Create Date: 2018-05-31 12:11:54.465015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import dataservice

# revision identifiers, used by Alembic.
revision = 'dbe23598a508'
down_revision = '8f1ad897fb0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('read_group',
    sa.Column('uuid', postgresql.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('paired_end', sa.Integer(), nullable=True),
    sa.Column('flow_cell', sa.Text(), nullable=True),
    sa.Column('lane_number', sa.Float(), nullable=True),
    sa.Column('quality_scale', sa.Text(), nullable=True),
    sa.Column('genomic_file_id', dataservice.api.common.model.KfId(length=11), nullable=False),
    sa.Column('kf_id', dataservice.api.common.model.KfId(length=11), nullable=False),
    sa.ForeignKeyConstraint(['genomic_file_id'], ['genomic_file.kf_id'], ),
    sa.PrimaryKeyConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('read_group')
    # ### end Alembic commands ###
