"""
Add is_harmonized, original_reference_genome to genomic_file

Revision ID: dc3be023c886
Revises: 99a46e736497
Create Date: 2018-03-30 16:11:47.107656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3be023c886'
down_revision = '99a46e736497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_file', sa.Column('is_harmonized', sa.Boolean(), nullable=True))
    op.add_column('genomic_file', sa.Column('original_reference_genome', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genomic_file', 'original_reference_genome')
    op.drop_column('genomic_file', 'is_harmonized')
    # ### end Alembic commands ###
