"""
1.4.4 - Add method_of_sample_procurement column to biospecimen

Revision ID: dd4c7a3ec1be
Revises: c89c99674f2c
Create Date: 2018-10-30 09:48:50.884254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4c7a3ec1be'
down_revision = 'c89c99674f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biospecimen', sa.Column('method_of_sample_procurement', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biospecimen', 'method_of_sample_procurement')
    # ### end Alembic commands ###
