"""empty message

Revision ID: dd9b18dce2d9
Revises: 
Create Date: 2018-01-24 17:15:12.361059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9b18dce2d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('data_type', sa.String(length=32), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('participant',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('demographic',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('race', sa.Text(), nullable=True),
    sa.Column('ethnicity', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('participant_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.kf_id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('participant_id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('sample',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('kf_id', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('tissue_type', sa.Text(), nullable=True),
    sa.Column('composition', sa.Text(), nullable=True),
    sa.Column('anatomical_site', sa.Text(), nullable=True),
    sa.Column('age_at_event_days', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.kf_id'], ),
    sa.PrimaryKeyConstraint('_id'),
    sa.UniqueConstraint('kf_id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample')
    op.drop_table('demographic')
    op.drop_table('participant')
    op.drop_table('file')
    # ### end Alembic commands ###
