"""
Change column type of concentration to float for aliquot table
Add mondo, ncit to diagnosis table

Revision ID: dda74cdf687d
Revises: 0ab7fe177917
Create Date: 2018-03-30 11:13:21.915197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda74cdf687d'
down_revision = '0ab7fe177917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aliquot', 'concentration',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('diagnosis', sa.Column('mondo', sa.Text(), nullable=True))
    op.add_column('diagnosis', sa.Column('ncit', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnosis', 'ncit')
    op.drop_column('diagnosis', 'mondo')
    op.alter_column('aliquot', 'concentration',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
