"""
1.8.1 Rename Participant.species to Participant.taxonomy

Revision ID: e37e013db6c7
Revises: 7ed804d54566
Create Date: 2019-12-05 16:47:28.022024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37e013db6c7'
down_revision = '7ed804d54566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('participant', sa.Column('taxonomy', sa.Text(), nullable=True))
    # op.drop_column('participant', 'species')
    op.alter_column('participant', 'species', new_column_name='taxonomy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('participant', sa.Column('species', sa.TEXT(), autoincrement=False, nullable=True))
    # op.drop_column('participant', 'taxonomy')
    op.alter_column('participant', 'taxonomy', new_column_name='species')
    # ### end Alembic commands ###
