"""
1.23.0

Rename biobank_contact to biobank_email
Add biobank_name column

Revision ID: f07d043290d0
Revises: 1f14248ec4cf
Create Date: 2024-06-06 14:54:46.201004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07d043290d0'
down_revision = '1f14248ec4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column(
        'biobank_email', sa.Text(), nullable=True))
    op.add_column('study', sa.Column('biobank_name', sa.Text(), nullable=True))
    op.drop_column('study', 'biobank_contact')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('biobank_contact',
                  sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('study', 'biobank_name')
    op.drop_column('study', 'biobank_email')
    # ### end Alembic commands ###
