"""
Add consent_type, family_id, is_proband to Participant entity

Revision ID: f62d630e7bd7
Revises: c1b8fdd17637
Create Date: 2018-02-15 15:39:52.007986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62d630e7bd7'
down_revision = 'c1b8fdd17637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'outcome', ['kf_id'])
    op.add_column('participant', sa.Column('consent_type', sa.Text(), nullable=True))
    op.add_column('participant', sa.Column('family_id', sa.Text(), nullable=True))
    op.add_column('participant', sa.Column('is_proband', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'is_proband')
    op.drop_column('participant', 'family_id')
    op.drop_column('participant', 'consent_type')
    op.drop_constraint(None, 'outcome', type_='unique')
    # ### end Alembic commands ###
