"""empty message

Revision ID: f80726457a72
Revises: 0cc35a21afc2
Create Date: 2018-02-07 16:12:38.279955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80726457a72'
down_revision = '0cc35a21afc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genomic_file', sa.Column('controlled_access', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genomic_file', 'controlled_access')
    # ### end Alembic commands ###
