"""
Add consent_type, family_id, is_proband fields to Participant

Revision ID: f91046108b04
Revises: c23f9043d57b
Create Date: 2018-02-16 13:59:54.578969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91046108b04'
down_revision = 'c23f9043d57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('consent_type', sa.Text(), nullable=True))
    op.add_column('participant', sa.Column('family_id', sa.Text(), nullable=True))
    op.add_column('participant', sa.Column('is_proband', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'is_proband')
    op.drop_column('participant', 'family_id')
    op.drop_column('participant', 'consent_type')
    # ### end Alembic commands ###
