"""
Temporary test migrations

Revision ID: fe2b0ea83ad7
Revises: 16e588cc6b85
Create Date: 2023-05-18 19:55:06.865732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import dataservice

# revision identifiers, used by Alembic.
revision = 'fe2b0ea83ad7'
down_revision = '16e588cc6b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foo',
                    sa.Column('uuid', postgresql.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(), nullable=True),
                    sa.Column('visible', sa.Boolean(),
                              server_default='true', nullable=False),
                    sa.Column('visibility_reason', sa.Text(), nullable=True),
                    sa.Column('visibility_comment', sa.Text(), nullable=True),
                    sa.Column('foo', sa.Text(), nullable=True),
                    sa.Column('number', sa.Integer(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.Column('participant_id', dataservice.api.common.model.KfId(
                        length=11), nullable=False),
                    sa.Column('kf_id', dataservice.api.common.model.KfId(
                        length=11), nullable=False),
                    sa.ForeignKeyConstraint(['participant_id'], [
                                            'participant.kf_id'], ),
                    sa.PrimaryKeyConstraint('kf_id'),
                    sa.UniqueConstraint('uuid')
                    )
    op.add_column('biospecimen', sa.Column('foo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biospecimen', 'foo')
    op.drop_table('foo')
    # ### end Alembic commands ###
