#!/bin/bash
set -e

function push_container() {
  set +e
  stderr=$(docker push "${ACCOUNT_ID}".dkr.ecr."${REGION}".amazonaws.com/${PROJECT_NAME}:"${GIT_COMMIT}")
  set -e
  #Check if tag already exists, skipping to push. Otherwise, SHA will change and it will cause issues in ECS.
  if [[ $stderr == *"immutable"* ]]; then
    echo "Tag already exists, ecr is immutable ... $stderr"
    echo "Error encounter exiting... $stderr"
    exit 1
  fi
}

#Attempt to set project name based on the git repo name
if [ -z $PROJECT_NAME ]; then
  PROJECT_NAME=$(basename -s .git $(git config --get remote.origin.url))
fi

if [ -z $REGION ]; then
  echo "Please provide REGION value (e.g. us-east-1)"
fi

REGION=${REGION}
ACCOUNT_ID=$(aws sts get-caller-identity --output text | awk '{print $1}')

if [[ -n "${GIT_COMMIT}" ]]; then
  GIT_COMMIT="${GIT_COMMIT:0:7}"
else
  GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

aws ecr get-login-password --region "${REGION}" | docker login --username AWS --password-stdin "${ACCOUNT_ID}".dkr.ecr."${REGION}".amazonaws.com
docker build --platform linux/amd64 -t ${PROJECT_NAME} .
docker tag ${PROJECT_NAME}:latest "${ACCOUNT_ID}".dkr.ecr."${REGION}".amazonaws.com/${PROJECT_NAME}:"${GIT_COMMIT}"

push_container
