name: 🧱 CI/CD Base Deployment

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      REGION:
        required: true
        type: string
      ACCOUNT:
        required: true
        type: string
      RUNNER:
        required: true
        type: string
      plan_dir:
        required: false
        default: ''
        type: string
        description: Directory of Terraform plans if directory structure is unique
      approvers:
        required: false
        type: string
        default: ${{ github.actor }}

jobs:
  plan:
    name: Run Terraform
    runs-on: ${{ inputs.RUNNER }}-linux-large
    env:
        environment: "${{ inputs.ENVIRONMENT }}"
        region: "${{ inputs.REGION }}"
        account: "${{ inputs.ACCOUNT }}"
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: GitHub Auth 
          uses: mobiledevops/secret-to-file-action@v1
          with:
              base64-encoded-secret: "${{ secrets.D3B_ID_RSA }}"
              filename: "id_rsa"
              is-executable: false 
              working-directory: "/home/ec2-user/.ssh"
        - name: Github Auth 
          run: |
            chmod 400 /home/ec2-user/.ssh/id_rsa
            ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
            ls -altr /home/ec2-user/.ssh/id_rsa
            openssl pkey -in /home/ec2-user/.ssh/id_rsa -noout
        - name: Install Terraform
          run: |
            install_with_retry() {
              max_attempts=5
              attempt_count=0
              success=false
              while [ $success = false ] && [ $attempt_count -le $max_attempts ]; do
                echo "Attempting $attempt_count/$max_attempts: Installing $*"
                sudo dnf install -y $*
              if [ $? -eq 0 ]; then
                  success=true
                else
                  echo "Failed to install $1 - retrying"
                  attempt_count=$(( attempt_count + 1 ))
                  sleep 5
                fi
              done
            }
            if ! command -v terraform; then
               install_with_retry dnf-plugins-core
               sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo               
               install_with_retry terraform
            else 
               echo "Terraform is already installed"
            fi
        - name: Terraform Plan 
          env:
            ACCOUNT: ${{ env.account }}
            ENVIRONMENT: ${{ env.environment }}
            REGION: ${{ env.region }}
          id: plan
          run: |
            ./deployment/scripts/infra plan
            cd ./deployment/terraform/
            terraform show -no-color plan.tfplan > tfplan.txt
            {
              echo "plan_output<<EOF"
              cat tfplan.txt 
              echo EOF
            } >> $GITHUB_OUTPUT
        - name: Skip approval if no changes
          id: any-changes
          run: |
            if echo '${{ steps.plan.outputs.plan_output }}' | grep -q 'no changes are needed'; then
                echo "status=skip" >> $GITHUB_OUTPUT
            else
                echo "status=continue" >> $GITHUB_OUTPUT
            fi
        - name: Print status and TF output
          run: |
            echo '${{ steps.any-changes.outputs.status }}'
            echo '${{ steps.plan.outputs.plan_output }}'
        - name: Manual Approval
          id: manual-approval 
          uses: trstringer/manual-approval@v1
          timeout-minutes: 30
          if: ${{ ( github.ref == 'refs/heads/master' ) && steps.any-changes.outputs.status == 'continue' }}
          with:
            secret: ${{ github.TOKEN }}
            approvers: ${{ inputs.approvers }}
            minimum-approvals: 1
            issue-title: "Deploying Terraform to ${{ inputs.ENVIRONMENT }} ${{ inputs.ACCOUNT }}"
            issue-body: "Please approve or deny the deployment.\n Plan:\n Please see logs"
        - name: Execute Apply
          if: ${{ ( github.ref == 'refs/heads/master' ) && steps.any-changes.outputs.status == 'continue' }}
          env:
            ACCOUNT: ${{ env.account }}
            ENVIRONMENT: ${{ env.environment }} 
            REGION: ${{ env.region }}
          run: ./deployment/scripts/infra apply
