name: Deployment 

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'main'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  issues: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        account: [kf-strides]
        region: [us-east-1]
    uses: ./.github/workflows/build.yml
    with:
      REGION: ${{ matrix.region }}
      ACCOUNT: ${{ matrix.account }}
      RUNNER: ${{ matrix.runner == '' && matrix.account || matrix.runner }}
    secrets: inherit
  deploy-dev:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        environment: [dev]
        account: [kf-strides]
        region: [us-east-1]
    uses: ./.github/workflows/cicd_base.yml
    with:
      ENVIRONMENT: ${{ matrix.environment }}
      REGION: ${{ matrix.region }}
      ACCOUNT: ${{ matrix.account }}
      RUNNER: ${{ matrix.runner == '' && matrix.account || matrix.runner }}
    secrets: inherit
  deploy-qa:
    needs: [build,deploy-dev]
    strategy:
      fail-fast: false
      matrix:
        environment: [qa]
        account: [kf-strides]
        region: [us-east-1]
    uses: ./.github/workflows/cicd_base.yml
    with:
      ENVIRONMENT: ${{ matrix.environment }}
      REGION: ${{ matrix.region }}
      ACCOUNT: ${{ matrix.account }}
      RUNNER: ${{ matrix.runner == '' && matrix.account || matrix.runner }}
    secrets: inherit
  deploy-prd:
    needs: [build,deploy-qa]
    strategy:
      fail-fast: false
      matrix:
        environment: [prd]
        account: [kf-strides]
        region: [us-east-1]
    uses: ./.github/workflows/cicd_base.yml
    with:
      ENVIRONMENT: ${{ matrix.environment }}
      REGION: ${{ matrix.region }}
      ACCOUNT: ${{ matrix.account }}
      RUNNER: ${{ matrix.runner == '' && matrix.account || matrix.runner }}
    secrets: inherit
