name: Build and Publish Image

on:
  push:
    branches:
      - "main"
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  build-publish-prd-image:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and Publish Image"
        run: |
          docker build . --tag ghcr.io/kids-first/kf-api-dataservice/kf-api-dataservice:${{ github.ref_name }}
          docker push ghcr.io/kids-first/kf-api-dataservice/kf-api-dataservice:${{ github.ref_name }}
  build-publish-dev-image:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and Publish Image"
        run: |
          docker build . --tag ghcr.io/kids-first/kf-api-dataservice/kf-api-dataservice:post-release-${ git tag --sort=committerdate | grep -E '[0-9]' | tail -1 | cut -b 1-7 }-${GITHUB_SHA:0:7}
          docker push ghcr.io/kids-first/kf-api-dataservice/kf-api-dataservice:post-release-${ git tag --sort=committerdate | grep -E '[0-9]' | tail -1 | cut -b 1-7 }-${GITHUB_SHA:0:7}
